# Puerto y Nombre
server.port=${PORT:8081}
spring.application.name=DaxApp

# Configuración de Base de Datos (Segura)
spring.datasource.url=${DB_URL:jdbc:postgresql://aws-1-us-east-2.pooler.supabase.com:5432/postgres}
spring.datasource.username=${DB_USER:postgres.rmxswgikhfkqxlxfojsf}
spring.datasource.password=${DB_PASSWORD:ssvuxy0nNXuude3y}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.properties.hibernate.default_schema=public
spring.datasource.hikari.keepaliveTime=30000

# Swagger / OpenAPI
springdoc.swagger-ui.path=/swagger-ui.html